-- OBJECTIVE QUESTIONS... FROM QUESTIONS 15 TO 21 :-


-- Q.15. Identify the top 5 doctors who generated the most revenue but had the fewest patients. (SQL)
			
            SELECT `Doctor Name` AS Doctor, SUM(`Total Bill`) AS Revenue, COUNT(DISTINCT patient_id) AS No_Of_Patients
			FROM doctor GROUP BY Doctor ORDER BY Revenue DESC , No_Of_Patients ASC LIMIT 5;




-- Q.16. Find the department where the average waiting time has decreased over three consecutive months. (SQL)
			
            WITH CTE AS
			(SELECT department_referral, `date`, ROUND(AVG(patient_waittime), 2) AS Average_Wait_Time
			FROM hospital GROUP BY department_referral, `date`),

			CTE2 AS
			(SELECT department_referral, `date`, Average_Wait_Time,
			LAG(Average_Wait_Time, 1) OVER (PARTITION BY department_referral ORDER BY `date`) AS Previous_1_Month_Average,
			LAG(Average_Wait_Time, 2) OVER (PARTITION BY department_referral ORDER BY `date`) AS Previous_2_Month_Average,
			LAG(Average_Wait_Time, 3) OVER (PARTITION BY department_referral ORDER BY `date`) AS Previous_3_Month_Average
			FROM CTE)

			SELECT department_referral FROM CTE2
			WHERE Average_Wait_Time < Previous_1_Month_Average
            AND Previous_1_Month_Average < Previous_2_Month_Average
            AND Previous_2_Month_Average < previous_3_month_average
			GROUP BY department_referral;




-- Q.17. Determine the ratio of male to female patients for each doctor and rank the doctors based on this ratio. (SQL)

			WITH CTE AS 
			(SELECT d.`Doctor Name` AS Doctor_Name,
			SUM(CASE WHEN h.patient_gender = "M" THEN 1 ELSE 0 END) AS Male_Count, SUM(CASE WHEN h.patient_gender = "F" THEN 1 ELSE 0 END) AS Female_Count
			FROM hospital h INNER JOIN doctor AS d ON h.patient_id = d.patient_id GROUP BY Doctor_Name),

			CTE2 AS
			(SELECT Doctor_Name, Male_Count, Female_Count, round((Male_Count / Female_Count),2) as Male_To_Female_Ratio FROM CTE)

			SELECT Doctor_Name, Male_Count, female_count, Male_To_Female_Ratio,
			DENSE_RANK() OVER(ORDER BY Male_To_Female_ratio DESC) AS Ranking 
			FROM CTE2;




-- Q.18. Calculate the average satisfaction score of patients for each doctor based on their visits. (SQL)

			SELECT d.`Doctor Name` AS Doctor_Name, ROUND(AVG(CASE WHEN h.patient_sat_score = "" THEN 5 ELSE h.patient_sat_score END),2) AS patient_sat_score
			FROM hospital h INNER JOIN doctor d ON h.patient_id = d.patient_id GROUP BY Doctor_Name ORDER BY patient_sat_score DESC;




-- Q.19. Find doctors who have treated patients from different races and calculate the diversity of their patient base. (SQL)

			SELECT d.`Doctor Name` AS Doctor_Name, COUNT(DISTINCT h.patient_race) AS differnet_race_count FROM hospital h
            INNER JOIN doctor d ON h.patient_id = d.patient_id GROUP BY Doctor_Name HAVING COUNT(DISTINCT h.patient_race) > 1 ORDER BY differnet_race_count DESC;




-- Q.20. Calculate the ratio of total bills generated by male patients to female patients for each department. (SQL)

			SELECT h.department_referral,
			SUM(CASE WHEN patient_gender = "M" THEN d.`Total Bill` END) AS Male_Total_Bill,
			SUM(CASE WHEN patient_gender = "F" THEN d.`Total Bill` END) AS Female_Total_Bill,
			ROUND(SUM(CASE WHEN patient_gender = "M" THEN d.`Total Bill` END) / SUM(CASE WHEN patient_gender = "F" then d.`Total Bill` end),2) as Male_To_Female_Ratio
			FROM hospital h INNER JOIN  doctor d ON h.patient_id = d.patient_id GROUP BY h.department_referral;




-- Q.21. Update the patient satisfaction score for all patients who visited the "General Practice" department and had a waiting time of more than 30 minutes. Increase their satisfaction score by 2 points, but ensure that the satisfaction score does not exceed 10. (SQL)

			UPDATE hospital
			SET patient_sat_score = LEAST(patient_sat_score + 2,10)
			WHERE LOWER(department_referral) = "general practice" AND patient_waittime > 30;